# Generated by Django 4.2.6 on 2025-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiccatoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], default='online', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='guitar_type',
            field=models.CharField(blank=True, choices=[('acoustic', 'Acoustic'), ('lead', 'Lead/Solo'), ('bass', 'Bass')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='schedule',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=20),
        ),
    ]
