# Generated by Django 4.2.6 on 2025-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiccatoapp', '0002_enrollment_mode_alter_enrollment_guitar_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='guardians_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
